# Generated by Django 4.2.7 on 2023-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadurl",
            name="downloaded",
            field=models.BooleanField(default=False),
        ),
    ]
