# Generated by Django 4.2.7 on 2023-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1", "0002_downloadurl_downloaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadurl",
            name="file_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
