# Generated by Django 4.2.7 on 2023-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1", "0003_alter_downloadurl_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadurl",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="downloadurl",
            name="loaded_to_db",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="downloadurl",
            name="text_file_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="downloadurl",
            name="text_file_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
