from django.db import models


class DownloadURL(models.Model):
    file_name = models.CharField(max_length=100, unique=True)
    created_by = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    url = models.URLField()
    downloaded = models.BooleanField(default=False)
    file_type = models.CharField(max_length=64, null=True, blank=True)
    text_file_name = models.CharField(
        max_length=100, null=True, blank=True
    )  # TODO remove these and create new table
    text_file_path = models.CharField(
        max_length=100, null=True, blank=True
    )  # TODO https://github.com/eddyizm/NPI_FILES/issues/21
    loaded_to_db = models.BooleanField(default=False)  # TODO

    def __str__(self):
        return self.file_name


class NpiRawData(models.Model):
    npi = models.CharField(db_column='NPI', max_length=255, blank=True, null=True)  # Field name made lowercase.
    entity_type_code = models.CharField(db_column='Entity Type Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    replacement_npi = models.CharField(db_column='Replacement NPI', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    employer_identification_number_ein_field = models.CharField(db_column='Employer Identification Number (EIN)', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters. Field renamed because it ended with '_'.
    provider_organization_name_legal_business_name_field = models.CharField(db_column='Provider Organization Name (Legal Business Name)', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters. Field renamed because it ended with '_'.
    provider_last_name_legal_name_field = models.CharField(db_column='Provider Last Name (Legal Name)', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters. Field renamed because it ended with '_'.
    provider_first_name = models.CharField(db_column='Provider First Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_middle_name = models.CharField(db_column='Provider Middle Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_name_prefix_text = models.CharField(db_column='Provider Name Prefix Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_name_suffix_text = models.CharField(db_column='Provider Name Suffix Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_credential_text = models.CharField(db_column='Provider Credential Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_organization_name = models.CharField(db_column='Provider Other Organization Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_organization_name_type_code = models.CharField(db_column='Provider Other Organization Name Type Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_last_name = models.CharField(db_column='Provider Other Last Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_first_name = models.CharField(db_column='Provider Other First Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_middle_name = models.CharField(db_column='Provider Other Middle Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_name_prefix_text = models.CharField(db_column='Provider Other Name Prefix Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_name_suffix_text = models.CharField(db_column='Provider Other Name Suffix Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_credential_text = models.CharField(db_column='Provider Other Credential Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_other_last_name_type_code = models.CharField(db_column='Provider Other Last Name Type Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_first_line_business_mailing_address = models.CharField(db_column='Provider First Line Business Mailing Address', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_second_line_business_mailing_address = models.CharField(db_column='Provider Second Line Business Mailing Address', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_mailing_address_city_name = models.CharField(db_column='Provider Business Mailing Address City Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_mailing_address_state_name = models.CharField(db_column='Provider Business Mailing Address State Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_mailing_address_postal_code = models.CharField(db_column='Provider Business Mailing Address Postal Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_mailing_address_country_code_if_outside_u_s_field = models.CharField(db_column='Provider Business Mailing Address Country Code (If outside U.S.', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters. Field renamed because it ended with '_'.
    provider_business_mailing_address_telephone_number = models.CharField(db_column='Provider Business Mailing Address Telephone Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_mailing_address_fax_number = models.CharField(db_column='Provider Business Mailing Address Fax Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_first_line_business_practice_location_address = models.CharField(db_column='Provider First Line Business Practice Location Address', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_second_line_business_practice_location_address = models.CharField(db_column='Provider Second Line Business Practice Location Address', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_practice_location_address_city_name = models.CharField(db_column='Provider Business Practice Location Address City Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_practice_location_address_state_name = models.CharField(db_column='Provider Business Practice Location Address State Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_practice_location_address_postal_code = models.CharField(db_column='Provider Business Practice Location Address Postal Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_practice_location_address_country_code_if_ou = models.CharField(db_column='Provider Business Practice Location Address Country Code (If ou', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_practice_location_address_telephone_number = models.CharField(db_column='Provider Business Practice Location Address Telephone Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_business_practice_location_address_fax_number = models.CharField(db_column='Provider Business Practice Location Address Fax Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_enumeration_date = models.CharField(db_column='Provider Enumeration Date', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    last_update_date = models.CharField(db_column='Last Update Date', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    npi_deactivation_reason_code = models.CharField(db_column='NPI Deactivation Reason Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    npi_deactivation_date = models.CharField(db_column='NPI Deactivation Date', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    npi_reactivation_date = models.CharField(db_column='NPI Reactivation Date', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_gender_code = models.CharField(db_column='Provider Gender Code', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_last_name = models.CharField(db_column='Authorized Official Last Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_first_name = models.CharField(db_column='Authorized Official First Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_middle_name = models.CharField(db_column='Authorized Official Middle Name', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_title_or_position = models.CharField(db_column='Authorized Official Title or Position', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_telephone_number = models.CharField(db_column='Authorized Official Telephone Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_1 = models.CharField(db_column='Healthcare Provider Taxonomy Code_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_1 = models.CharField(db_column='Provider License Number_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_1 = models.CharField(db_column='Provider License Number State Code_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_1 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_2 = models.CharField(db_column='Healthcare Provider Taxonomy Code_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_2 = models.CharField(db_column='Provider License Number_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_2 = models.CharField(db_column='Provider License Number State Code_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_2 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_3 = models.CharField(db_column='Healthcare Provider Taxonomy Code_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_3 = models.CharField(db_column='Provider License Number_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_3 = models.CharField(db_column='Provider License Number State Code_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_3 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_4 = models.CharField(db_column='Healthcare Provider Taxonomy Code_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_4 = models.CharField(db_column='Provider License Number_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_4 = models.CharField(db_column='Provider License Number State Code_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_4 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_5 = models.CharField(db_column='Healthcare Provider Taxonomy Code_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_5 = models.CharField(db_column='Provider License Number_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_5 = models.CharField(db_column='Provider License Number State Code_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_5 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_6 = models.CharField(db_column='Healthcare Provider Taxonomy Code_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_6 = models.CharField(db_column='Provider License Number_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_6 = models.CharField(db_column='Provider License Number State Code_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_6 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_7 = models.CharField(db_column='Healthcare Provider Taxonomy Code_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_7 = models.CharField(db_column='Provider License Number_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_7 = models.CharField(db_column='Provider License Number State Code_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_7 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_8 = models.CharField(db_column='Healthcare Provider Taxonomy Code_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_8 = models.CharField(db_column='Provider License Number_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_8 = models.CharField(db_column='Provider License Number State Code_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_8 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_9 = models.CharField(db_column='Healthcare Provider Taxonomy Code_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_9 = models.CharField(db_column='Provider License Number_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_9 = models.CharField(db_column='Provider License Number State Code_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_9 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_10 = models.CharField(db_column='Healthcare Provider Taxonomy Code_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_10 = models.CharField(db_column='Provider License Number_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_10 = models.CharField(db_column='Provider License Number State Code_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_10 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_11 = models.CharField(db_column='Healthcare Provider Taxonomy Code_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_11 = models.CharField(db_column='Provider License Number_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_11 = models.CharField(db_column='Provider License Number State Code_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_11 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_12 = models.CharField(db_column='Healthcare Provider Taxonomy Code_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_12 = models.CharField(db_column='Provider License Number_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_12 = models.CharField(db_column='Provider License Number State Code_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_12 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_13 = models.CharField(db_column='Healthcare Provider Taxonomy Code_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_13 = models.CharField(db_column='Provider License Number_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_13 = models.CharField(db_column='Provider License Number State Code_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_13 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_14 = models.CharField(db_column='Healthcare Provider Taxonomy Code_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_14 = models.CharField(db_column='Provider License Number_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_14 = models.CharField(db_column='Provider License Number State Code_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_14 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_code_15 = models.CharField(db_column='Healthcare Provider Taxonomy Code_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_15 = models.CharField(db_column='Provider License Number_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provider_license_number_state_code_15 = models.CharField(db_column='Provider License Number State Code_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_primary_taxonomy_switch_15 = models.CharField(db_column='Healthcare Provider Primary Taxonomy Switch_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_1 = models.CharField(db_column='Other Provider Identifier_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_1 = models.CharField(db_column='Other Provider Identifier Type Code_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_1 = models.CharField(db_column='Other Provider Identifier State_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_1 = models.CharField(db_column='Other Provider Identifier Issuer_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_2 = models.CharField(db_column='Other Provider Identifier_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_2 = models.CharField(db_column='Other Provider Identifier Type Code_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_2 = models.CharField(db_column='Other Provider Identifier State_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_2 = models.CharField(db_column='Other Provider Identifier Issuer_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_3 = models.CharField(db_column='Other Provider Identifier_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_3 = models.CharField(db_column='Other Provider Identifier Type Code_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_3 = models.CharField(db_column='Other Provider Identifier State_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_3 = models.CharField(db_column='Other Provider Identifier Issuer_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_4 = models.CharField(db_column='Other Provider Identifier_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_4 = models.CharField(db_column='Other Provider Identifier Type Code_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_4 = models.CharField(db_column='Other Provider Identifier State_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_4 = models.CharField(db_column='Other Provider Identifier Issuer_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_5 = models.CharField(db_column='Other Provider Identifier_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_5 = models.CharField(db_column='Other Provider Identifier Type Code_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_5 = models.CharField(db_column='Other Provider Identifier State_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_5 = models.CharField(db_column='Other Provider Identifier Issuer_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_6 = models.CharField(db_column='Other Provider Identifier_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_6 = models.CharField(db_column='Other Provider Identifier Type Code_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_6 = models.CharField(db_column='Other Provider Identifier State_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_6 = models.CharField(db_column='Other Provider Identifier Issuer_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_7 = models.CharField(db_column='Other Provider Identifier_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_7 = models.CharField(db_column='Other Provider Identifier Type Code_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_7 = models.CharField(db_column='Other Provider Identifier State_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_7 = models.CharField(db_column='Other Provider Identifier Issuer_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_8 = models.CharField(db_column='Other Provider Identifier_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_8 = models.CharField(db_column='Other Provider Identifier Type Code_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_8 = models.CharField(db_column='Other Provider Identifier State_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_8 = models.CharField(db_column='Other Provider Identifier Issuer_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_9 = models.CharField(db_column='Other Provider Identifier_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_9 = models.CharField(db_column='Other Provider Identifier Type Code_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_9 = models.CharField(db_column='Other Provider Identifier State_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_9 = models.CharField(db_column='Other Provider Identifier Issuer_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_10 = models.CharField(db_column='Other Provider Identifier_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_10 = models.CharField(db_column='Other Provider Identifier Type Code_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_10 = models.CharField(db_column='Other Provider Identifier State_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_10 = models.CharField(db_column='Other Provider Identifier Issuer_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_11 = models.CharField(db_column='Other Provider Identifier_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_11 = models.CharField(db_column='Other Provider Identifier Type Code_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_11 = models.CharField(db_column='Other Provider Identifier State_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_11 = models.CharField(db_column='Other Provider Identifier Issuer_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_12 = models.CharField(db_column='Other Provider Identifier_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_12 = models.CharField(db_column='Other Provider Identifier Type Code_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_12 = models.CharField(db_column='Other Provider Identifier State_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_12 = models.CharField(db_column='Other Provider Identifier Issuer_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_13 = models.CharField(db_column='Other Provider Identifier_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_13 = models.CharField(db_column='Other Provider Identifier Type Code_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_13 = models.CharField(db_column='Other Provider Identifier State_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_13 = models.CharField(db_column='Other Provider Identifier Issuer_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_14 = models.CharField(db_column='Other Provider Identifier_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_14 = models.CharField(db_column='Other Provider Identifier Type Code_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_14 = models.CharField(db_column='Other Provider Identifier State_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_14 = models.CharField(db_column='Other Provider Identifier Issuer_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_15 = models.CharField(db_column='Other Provider Identifier_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_15 = models.CharField(db_column='Other Provider Identifier Type Code_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_15 = models.CharField(db_column='Other Provider Identifier State_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_15 = models.CharField(db_column='Other Provider Identifier Issuer_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_16 = models.CharField(db_column='Other Provider Identifier_16', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_16 = models.CharField(db_column='Other Provider Identifier Type Code_16', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_16 = models.CharField(db_column='Other Provider Identifier State_16', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_16 = models.CharField(db_column='Other Provider Identifier Issuer_16', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_17 = models.CharField(db_column='Other Provider Identifier_17', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_17 = models.CharField(db_column='Other Provider Identifier Type Code_17', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_17 = models.CharField(db_column='Other Provider Identifier State_17', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_17 = models.CharField(db_column='Other Provider Identifier Issuer_17', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_18 = models.CharField(db_column='Other Provider Identifier_18', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_18 = models.CharField(db_column='Other Provider Identifier Type Code_18', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_18 = models.CharField(db_column='Other Provider Identifier State_18', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_18 = models.CharField(db_column='Other Provider Identifier Issuer_18', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_19 = models.CharField(db_column='Other Provider Identifier_19', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_19 = models.CharField(db_column='Other Provider Identifier Type Code_19', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_19 = models.CharField(db_column='Other Provider Identifier State_19', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_19 = models.CharField(db_column='Other Provider Identifier Issuer_19', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_20 = models.CharField(db_column='Other Provider Identifier_20', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_20 = models.CharField(db_column='Other Provider Identifier Type Code_20', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_20 = models.CharField(db_column='Other Provider Identifier State_20', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_20 = models.CharField(db_column='Other Provider Identifier Issuer_20', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_21 = models.CharField(db_column='Other Provider Identifier_21', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_21 = models.CharField(db_column='Other Provider Identifier Type Code_21', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_21 = models.CharField(db_column='Other Provider Identifier State_21', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_21 = models.CharField(db_column='Other Provider Identifier Issuer_21', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_22 = models.CharField(db_column='Other Provider Identifier_22', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_22 = models.CharField(db_column='Other Provider Identifier Type Code_22', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_22 = models.CharField(db_column='Other Provider Identifier State_22', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_22 = models.CharField(db_column='Other Provider Identifier Issuer_22', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_23 = models.CharField(db_column='Other Provider Identifier_23', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_23 = models.CharField(db_column='Other Provider Identifier Type Code_23', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_23 = models.CharField(db_column='Other Provider Identifier State_23', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_23 = models.CharField(db_column='Other Provider Identifier Issuer_23', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_24 = models.CharField(db_column='Other Provider Identifier_24', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_24 = models.CharField(db_column='Other Provider Identifier Type Code_24', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_24 = models.CharField(db_column='Other Provider Identifier State_24', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_24 = models.CharField(db_column='Other Provider Identifier Issuer_24', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_25 = models.CharField(db_column='Other Provider Identifier_25', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_25 = models.CharField(db_column='Other Provider Identifier Type Code_25', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_25 = models.CharField(db_column='Other Provider Identifier State_25', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_25 = models.CharField(db_column='Other Provider Identifier Issuer_25', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_26 = models.CharField(db_column='Other Provider Identifier_26', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_26 = models.CharField(db_column='Other Provider Identifier Type Code_26', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_26 = models.CharField(db_column='Other Provider Identifier State_26', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_26 = models.CharField(db_column='Other Provider Identifier Issuer_26', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_27 = models.CharField(db_column='Other Provider Identifier_27', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_27 = models.CharField(db_column='Other Provider Identifier Type Code_27', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_27 = models.CharField(db_column='Other Provider Identifier State_27', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_27 = models.CharField(db_column='Other Provider Identifier Issuer_27', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_28 = models.CharField(db_column='Other Provider Identifier_28', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_28 = models.CharField(db_column='Other Provider Identifier Type Code_28', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_28 = models.CharField(db_column='Other Provider Identifier State_28', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_28 = models.CharField(db_column='Other Provider Identifier Issuer_28', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_29 = models.CharField(db_column='Other Provider Identifier_29', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_29 = models.CharField(db_column='Other Provider Identifier Type Code_29', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_29 = models.CharField(db_column='Other Provider Identifier State_29', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_29 = models.CharField(db_column='Other Provider Identifier Issuer_29', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_30 = models.CharField(db_column='Other Provider Identifier_30', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_30 = models.CharField(db_column='Other Provider Identifier Type Code_30', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_30 = models.CharField(db_column='Other Provider Identifier State_30', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_30 = models.CharField(db_column='Other Provider Identifier Issuer_30', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_31 = models.CharField(db_column='Other Provider Identifier_31', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_31 = models.CharField(db_column='Other Provider Identifier Type Code_31', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_31 = models.CharField(db_column='Other Provider Identifier State_31', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_31 = models.CharField(db_column='Other Provider Identifier Issuer_31', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_32 = models.CharField(db_column='Other Provider Identifier_32', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_32 = models.CharField(db_column='Other Provider Identifier Type Code_32', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_32 = models.CharField(db_column='Other Provider Identifier State_32', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_32 = models.CharField(db_column='Other Provider Identifier Issuer_32', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_33 = models.CharField(db_column='Other Provider Identifier_33', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_33 = models.CharField(db_column='Other Provider Identifier Type Code_33', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_33 = models.CharField(db_column='Other Provider Identifier State_33', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_33 = models.CharField(db_column='Other Provider Identifier Issuer_33', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_34 = models.CharField(db_column='Other Provider Identifier_34', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_34 = models.CharField(db_column='Other Provider Identifier Type Code_34', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_34 = models.CharField(db_column='Other Provider Identifier State_34', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_34 = models.CharField(db_column='Other Provider Identifier Issuer_34', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_35 = models.CharField(db_column='Other Provider Identifier_35', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_35 = models.CharField(db_column='Other Provider Identifier Type Code_35', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_35 = models.CharField(db_column='Other Provider Identifier State_35', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_35 = models.CharField(db_column='Other Provider Identifier Issuer_35', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_36 = models.CharField(db_column='Other Provider Identifier_36', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_36 = models.CharField(db_column='Other Provider Identifier Type Code_36', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_36 = models.CharField(db_column='Other Provider Identifier State_36', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_36 = models.CharField(db_column='Other Provider Identifier Issuer_36', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_37 = models.CharField(db_column='Other Provider Identifier_37', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_37 = models.CharField(db_column='Other Provider Identifier Type Code_37', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_37 = models.CharField(db_column='Other Provider Identifier State_37', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_37 = models.CharField(db_column='Other Provider Identifier Issuer_37', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_38 = models.CharField(db_column='Other Provider Identifier_38', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_38 = models.CharField(db_column='Other Provider Identifier Type Code_38', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_38 = models.CharField(db_column='Other Provider Identifier State_38', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_38 = models.CharField(db_column='Other Provider Identifier Issuer_38', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_39 = models.CharField(db_column='Other Provider Identifier_39', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_39 = models.CharField(db_column='Other Provider Identifier Type Code_39', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_39 = models.CharField(db_column='Other Provider Identifier State_39', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_39 = models.CharField(db_column='Other Provider Identifier Issuer_39', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_40 = models.CharField(db_column='Other Provider Identifier_40', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_40 = models.CharField(db_column='Other Provider Identifier Type Code_40', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_40 = models.CharField(db_column='Other Provider Identifier State_40', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_40 = models.CharField(db_column='Other Provider Identifier Issuer_40', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_41 = models.CharField(db_column='Other Provider Identifier_41', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_41 = models.CharField(db_column='Other Provider Identifier Type Code_41', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_41 = models.CharField(db_column='Other Provider Identifier State_41', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_41 = models.CharField(db_column='Other Provider Identifier Issuer_41', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_42 = models.CharField(db_column='Other Provider Identifier_42', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_42 = models.CharField(db_column='Other Provider Identifier Type Code_42', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_42 = models.CharField(db_column='Other Provider Identifier State_42', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_42 = models.CharField(db_column='Other Provider Identifier Issuer_42', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_43 = models.CharField(db_column='Other Provider Identifier_43', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_43 = models.CharField(db_column='Other Provider Identifier Type Code_43', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_43 = models.CharField(db_column='Other Provider Identifier State_43', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_43 = models.CharField(db_column='Other Provider Identifier Issuer_43', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_44 = models.CharField(db_column='Other Provider Identifier_44', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_44 = models.CharField(db_column='Other Provider Identifier Type Code_44', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_44 = models.CharField(db_column='Other Provider Identifier State_44', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_44 = models.CharField(db_column='Other Provider Identifier Issuer_44', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_45 = models.CharField(db_column='Other Provider Identifier_45', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_45 = models.CharField(db_column='Other Provider Identifier Type Code_45', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_45 = models.CharField(db_column='Other Provider Identifier State_45', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_45 = models.CharField(db_column='Other Provider Identifier Issuer_45', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_46 = models.CharField(db_column='Other Provider Identifier_46', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_46 = models.CharField(db_column='Other Provider Identifier Type Code_46', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_46 = models.CharField(db_column='Other Provider Identifier State_46', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_46 = models.CharField(db_column='Other Provider Identifier Issuer_46', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_47 = models.CharField(db_column='Other Provider Identifier_47', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_47 = models.CharField(db_column='Other Provider Identifier Type Code_47', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_47 = models.CharField(db_column='Other Provider Identifier State_47', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_47 = models.CharField(db_column='Other Provider Identifier Issuer_47', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_48 = models.CharField(db_column='Other Provider Identifier_48', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_48 = models.CharField(db_column='Other Provider Identifier Type Code_48', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_48 = models.CharField(db_column='Other Provider Identifier State_48', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_48 = models.CharField(db_column='Other Provider Identifier Issuer_48', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_49 = models.CharField(db_column='Other Provider Identifier_49', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_49 = models.CharField(db_column='Other Provider Identifier Type Code_49', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_49 = models.CharField(db_column='Other Provider Identifier State_49', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_49 = models.CharField(db_column='Other Provider Identifier Issuer_49', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_50 = models.CharField(db_column='Other Provider Identifier_50', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_type_code_50 = models.CharField(db_column='Other Provider Identifier Type Code_50', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_state_50 = models.CharField(db_column='Other Provider Identifier State_50', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    other_provider_identifier_issuer_50 = models.CharField(db_column='Other Provider Identifier Issuer_50', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    is_sole_proprietor = models.CharField(db_column='Is Sole Proprietor', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    is_organization_subpart = models.CharField(db_column='Is Organization Subpart', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    parent_organization_lbn = models.CharField(db_column='Parent Organization LBN', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    parent_organization_tin = models.CharField(db_column='Parent Organization TIN', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_name_prefix_text = models.CharField(db_column='Authorized Official Name Prefix Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_name_suffix_text = models.CharField(db_column='Authorized Official Name Suffix Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    authorized_official_credential_text = models.CharField(db_column='Authorized Official Credential Text', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_1 = models.CharField(db_column='Healthcare Provider Taxonomy Group_1', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_2 = models.CharField(db_column='Healthcare Provider Taxonomy Group_2', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_3 = models.CharField(db_column='Healthcare Provider Taxonomy Group_3', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_4 = models.CharField(db_column='Healthcare Provider Taxonomy Group_4', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_5 = models.CharField(db_column='Healthcare Provider Taxonomy Group_5', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_6 = models.CharField(db_column='Healthcare Provider Taxonomy Group_6', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_7 = models.CharField(db_column='Healthcare Provider Taxonomy Group_7', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_8 = models.CharField(db_column='Healthcare Provider Taxonomy Group_8', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_9 = models.CharField(db_column='Healthcare Provider Taxonomy Group_9', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_10 = models.CharField(db_column='Healthcare Provider Taxonomy Group_10', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_11 = models.CharField(db_column='Healthcare Provider Taxonomy Group_11', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_12 = models.CharField(db_column='Healthcare Provider Taxonomy Group_12', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_13 = models.CharField(db_column='Healthcare Provider Taxonomy Group_13', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_14 = models.CharField(db_column='Healthcare Provider Taxonomy Group_14', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    healthcare_provider_taxonomy_group_15 = models.CharField(db_column='Healthcare Provider Taxonomy Group_15', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    certification_date = models.CharField(db_column='Certification Date', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.

    # TODO remove ID and make NPI field primary key/index
    # class Meta:
    #     managed = False
    #     db_table = 'npi_raw_data'
